import "./globals.css";
import type { Metadata, Viewport } from "next";
import Script from "next/script";
import { Footer } from "./Footer";

// Microsoft Clarity — session-replay + heatmap analytics. Free, no PII
// collection by default, gives us watch-real-people-use-the-product
// recordings + click maps + rage-click detection. Insights we feed back
// into UX iterations.
//
// Activate by setting NEXT_PUBLIC_CLARITY_PROJECT_ID in the Vercel
// environment. Until then this is a no-op — nothing renders, no script
// loads. Set the env var via:
//   1. clarity.microsoft.com → New Project → SyncedIn (https://syncedin.org)
//   2. Copy the project ID (the string in the snippet's clarity("...") call)
//   3. Vercel → SyncedIn project → Settings → Env Vars → add
//      NEXT_PUBLIC_CLARITY_PROJECT_ID = <id> for Production + Preview
//   4. Redeploy
const CLARITY_PROJECT_ID = process.env.NEXT_PUBLIC_CLARITY_PROJECT_ID;

const SITE_URL =
  process.env.NEXT_PUBLIC_APP_URL?.replace(/\/$/, "") || "https://syncedin.org";
const SITE_TITLE =
  "SyncedIn | Where staying Synced to your network is seamless";
const SITE_DESCRIPTION =
  "Build a digital twin. Your twin talks to theirs. The two clones find the highest win-win between you, while you stay in control of every message.";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: SITE_TITLE,
    template: "%s · SyncedIn"
  },
  description: SITE_DESCRIPTION,
  manifest: "/manifest.json",
  appleWebApp: {
    capable: true,
    statusBarStyle: "black-translucent",
    title: "SyncedIn"
  },
  openGraph: {
    type: "website",
    siteName: "SyncedIn",
    title: SITE_TITLE,
    description: SITE_DESCRIPTION,
    url: SITE_URL
    // images is auto-generated by Next.js from app/opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: SITE_TITLE,
    description: SITE_DESCRIPTION
    // images is auto-generated by Next.js from app/twitter-image.tsx
  }
};

export const viewport: Viewport = {
  themeColor: "#080a12",
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="light">
      <head>
        {/* Apply the saved theme before paint so there's no flash. */}
        <script
          dangerouslySetInnerHTML={{
            __html:
              "try{var t=localStorage.getItem('syncedin-theme');if(t){document.documentElement.dataset.theme=t;}}catch(e){}"
          }}
        />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&family=IBM+Plex+Mono:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="min-h-screen">
        {children}
        <Footer />
        {/* Microsoft Clarity — loads only when the env var is set, so
            local + preview branches without the key are unaffected.
            Strategy "afterInteractive" means the page is interactive
            first, the snippet loads in the background. */}
        {CLARITY_PROJECT_ID && (
          <Script
            id="ms-clarity"
            strategy="afterInteractive"
            dangerouslySetInnerHTML={{
              __html: `(function(c,l,a,r,i,t,y){
        c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
        t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
        y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
      })(window, document, "clarity", "script", "${CLARITY_PROJECT_ID}");`
            }}
          />
        )}
      </body>
    </html>
  );
}
