import "./globals.css";
import type { Metadata, Viewport } from "next";
import { Footer } from "./Footer";

const SITE_URL =
  process.env.NEXT_PUBLIC_APP_URL?.replace(/\/$/, "") || "https://syncedin.org";
const SITE_TITLE =
  "SyncedIn — an agent-to-agent protocol between people";
const SITE_DESCRIPTION =
  "Build a digital twin. Your twin talks to theirs. The two clones find the highest win-win between you, while you stay in control of every message.";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: SITE_TITLE,
    template: "%s · SyncedIn"
  },
  description: SITE_DESCRIPTION,
  manifest: "/manifest.json",
  appleWebApp: {
    capable: true,
    statusBarStyle: "black-translucent",
    title: "SyncedIn"
  },
  openGraph: {
    type: "website",
    siteName: "SyncedIn",
    title: SITE_TITLE,
    description: SITE_DESCRIPTION,
    url: SITE_URL
    // images is auto-generated by Next.js from app/opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: SITE_TITLE,
    description: SITE_DESCRIPTION
    // images is auto-generated by Next.js from app/twitter-image.tsx
  }
};

export const viewport: Viewport = {
  themeColor: "#080a12",
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="light">
      <head>
        {/* Apply the saved theme before paint so there's no flash. */}
        <script
          dangerouslySetInnerHTML={{
            __html:
              "try{var t=localStorage.getItem('syncedin-theme');if(t){document.documentElement.dataset.theme=t;}}catch(e){}"
          }}
        />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&family=IBM+Plex+Mono:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="min-h-screen">
        {children}
        <Footer />
      </body>
    </html>
  );
}
