"use client";

import { useEffect, useState } from "react";
import { Wordmark } from "./Wordmark";
import Link from "next/link";

/**
 * MobileShell — client wrapper that ONLY renders on mobile (≤ lg breakpoint).
 *
 * On mobile the sidebar was rendering as a full-width column stacked above
 * the page content. With the new sci-fi-upload SyncMeter (which has a 50px
 * magenta drop-shadow), the dashboard's main column would render the meter
 * RIGHT ON TOP of the sidebar list. Looked broken.
 *
 * This component:
 *   1. Renders a thin top bar with [☰] + wordmark + theme toggle.
 *   2. Hides the desktop sidebar entirely on screens < lg.
 *   3. Toggles a slide-in drawer that holds the full sidebar content
 *      when the hamburger is tapped.
 *
 * AppShell still owns the desktop sidebar — it's wrapped in
 * `<div className="hidden lg:block">` so it disappears on mobile, and
 * MobileShell takes over the navigation chrome for ≤lg.
 */
export function MobileShell({ children }: { children: React.ReactNode }) {
  const [open, setOpen] = useState(false);

  // Close drawer on route change. Detect via popstate since Next 14 App
  // Router doesn't expose a low-level "route changed" hook in the same way.
  useEffect(() => {
    function onNav() {
      setOpen(false);
    }
    window.addEventListener("popstate", onNav);
    return () => window.removeEventListener("popstate", onNav);
  }, []);

  // Body scroll lock when drawer is open
  useEffect(() => {
    if (!open) return;
    const prev = document.body.style.overflow;
    document.body.style.overflow = "hidden";
    return () => {
      document.body.style.overflow = prev;
    };
  }, [open]);

  return (
    <>
      {/* Top mobile bar — kept thin. Padding + button height + wordmark
          height all sized so the bar lands at ~44px total. Earlier
          version ate ~30% of phone viewport height because the wordmark
          rendered at natural ~60px tall.

          CRITICAL: `display` MUST stay in the className, not the inline
          style. Inline-style `display: flex` outranks Tailwind's
          `lg:hidden` (which sets `display: none` at lg+), and the bar
          starts leaking onto desktop. Bug shipped once already. */}
      <div
        className="flex lg:hidden items-center"
        style={{
          position: "sticky",
          top: 0,
          zIndex: 40,
          background: "var(--panel-solid)",
          borderBottom: "1px solid var(--border)",
          padding: "4px 10px",
          gap: 10,
          minHeight: 56
        }}
      >
        <button
          type="button"
          onClick={() => setOpen((v) => !v)}
          aria-label="Open menu"
          style={{
            width: 40,
            height: 40,
            borderRadius: 10,
            border: "1px solid var(--border-bright)",
            background: "transparent",
            display: "inline-flex",
            alignItems: "center",
            justifyContent: "center",
            // line-height:1 + matching font-size makes the glyph render
            // optically centered in the box (default line-height was
            // pushing the ☰ glyph slightly above center).
            lineHeight: 1,
            cursor: "pointer",
            color: "var(--text)",
            fontSize: 20,
            flexShrink: 0,
            // Equal padding on all sides so the SVG glyph sits dead
            // center regardless of font-metric quirks.
            padding: 0
          }}
        >
          {open ? "✕" : "☰"}
        </button>
        <Link
          href="/"
          aria-label="SyncedIn — home"
          style={{
            display: "inline-flex",
            alignItems: "center",
            height: 44,
            textDecoration: "none",
            flexShrink: 0
          }}
        >
          {/*
            Every prior "make it bigger" iteration failed because the
            wordmark PNG is 500x500 with the actual glyph occupying
            only the middle ~94px band — 80% of the file was empty
            transparent space. Setting height: 72 was rendering an
            ACTUAL visible logo of ~15px tall.

            Fix: use the tight-cropped variant (438x106, generated by
            scripts) so the CSS height matches what the eye sees.
            44px on the tight crop reads roughly the same visual size
            as 200px on the padded original — finally big enough.
          */}
          <img
            src="/syncedin-wordmark-tight.png"
            alt="SyncedIn"
            className="wordmark-themed"
            height={44}
            style={{ height: 44, width: "auto", display: "block" }}
          />
        </Link>
      </div>

      {/* Drawer + scrim — slides in from left when open. Same
          inline-style vs Tailwind specificity caveat as above: do NOT
          set `display` inline; let `lg:hidden` win at lg+. We control
          interactivity via pointerEvents, not display, so the drawer
          can still animate when open changes on mobile. */}
      <div
        className="lg:hidden"
        aria-hidden={!open}
        style={{
          position: "fixed",
          inset: 0,
          zIndex: 50,
          pointerEvents: open ? "auto" : "none"
        }}
      >
        {/* Scrim */}
        <div
          onClick={() => setOpen(false)}
          style={{
            position: "absolute",
            inset: 0,
            background: "rgba(10, 13, 24, 0.55)",
            opacity: open ? 1 : 0,
            transition: "opacity 180ms ease"
          }}
        />
        {/* Sliding drawer — pulls in the desktop Sidebar content.
            The wordmark + its big top padding inside the Sidebar are
            HIDDEN here because the mobile top bar already shows the
            wordmark; rendering it again wasted ~140px of drawer height
            and pushed every nav item far down. CSS-scoped to the drawer
            via the class below so the desktop sidebar is unaffected. */}
        <div
          className="syncedin-mobile-drawer"
          style={{
            position: "absolute",
            top: 0,
            bottom: 0,
            left: 0,
            width: "min(280px, 86vw)",
            background: "var(--panel-solid)",
            borderRight: "1px solid var(--border)",
            transform: open ? "translateX(0)" : "translateX(-100%)",
            transition: "transform 220ms cubic-bezier(0.2, 0.8, 0.2, 1)",
            overflowY: "auto",
            // Pulled top padding entirely; the sweep band below
            // serves as the visual top edge and signals motion.
            padding: "0 6px 12px"
          }}
        >
          {/* Animated brand-gradient sweep band — sits at the very top of
              the drawer. Replaces the dead band of empty space the user
              saw with a thin, always-moving accent that says "this app
              is alive" without competing with the nav items below. 3px
              tall, 4s linear loop, no perf cost (pure CSS background-
              position shift). */}
          <div
            aria-hidden="true"
            style={{
              height: 3,
              width: "100%",
              background:
                "linear-gradient(90deg, #1f8bff 0%, #6b2dc9 25%, #d83bff 50%, #6b2dc9 75%, #1f8bff 100%)",
              backgroundSize: "200% 100%",
              animation: "drawerSweep 4s linear infinite",
              marginBottom: 6
            }}
          />
          {children}
        </div>
        <style>{`
          /* Wordmark is now SHOWN inside the mobile drawer too (Jack:
             "on mobile in menu logo isnt visible lets bring that back").
             The hide rules below used to kill it because earlier the
             drawer had its own top bar; now the drawer's only chrome is
             the 3px sweep band, so the Sidebar's wordmark gets to act
             as the menu header without competing. We still keep tight
             padding overrides so the nav items don't sit miles below
             the wordmark. */
          .syncedin-mobile-drawer > div {
            padding-top: 6px !important;
            padding-left: 6px !important;
            padding-right: 6px !important;
            gap: 6px !important;
          }
          .syncedin-mobile-drawer img.wordmark-themed,
          .syncedin-mobile-drawer img[src*="syncedin-wordmark"] {
            max-height: 28px !important;
            width: auto !important;
          }
          @keyframes drawerSweep {
            0%   { background-position: 0% 50%; }
            100% { background-position: 200% 50%; }
          }
        `}</style>
      </div>
    </>
  );
}
