#!/usr/bin/env bash
#
# SyncedIn Android release-bundle setup.
#
# One-time keystore generation + signing config + signed bundle build.
# Output: ~/twinlink/android/app/build/outputs/bundle/release/app-release.aab
# which you upload to Play Console → Internal Testing.
#
# Uses Play App Signing — Google manages the actual production release
# key, so this script generates an UPLOAD key only. If you lose the
# upload key, you can request a new one from Play Console (unlike the
# release key, which would be permanently lost).
#
# Default upload-key password is "syncedin-upload-2026" — change it via
# the UPLOAD_PASSWORD env var if you want something stronger.
#
# Usage:
#   cd ~/twinlink && bash scripts/android-release-setup.sh
#

set -e

ANDROID_DIR="$HOME/twinlink/android"
KEYSTORE="$ANDROID_DIR/app/syncedin-upload.jks"
ALIAS="syncedin"
PASSWORD="${UPLOAD_PASSWORD:-syncedin-upload-2026}"
DNAME="CN=Jackson Jesionowski, OU=SyncedIn, O=Full Body Zen LLC, L=San Francisco, ST=CA, C=US"

cd "$ANDROID_DIR"

# ─────────────────────────────────────────────────────────────
# 1. Generate the upload keystore (skip if it already exists).
# ─────────────────────────────────────────────────────────────
if [[ ! -f "$KEYSTORE" ]]; then
  echo "→ Generating upload keystore at $KEYSTORE"
  keytool -genkey -v \
    -keystore "$KEYSTORE" \
    -alias "$ALIAS" \
    -keyalg RSA \
    -keysize 2048 \
    -validity 25000 \
    -storepass "$PASSWORD" \
    -keypass "$PASSWORD" \
    -dname "$DNAME"
  echo "✓ Keystore generated. BACK THIS FILE UP: $KEYSTORE"
  echo "  Password: $PASSWORD  (save to your password manager)"
else
  echo "✓ Keystore already exists at $KEYSTORE — skipping generation"
fi

# ─────────────────────────────────────────────────────────────
# 2. Write signing credentials to gradle.properties so the
#    build.gradle block can reference them by name (don't ship
#    these to git — already in .gitignore via the leading
#    syncedin- prefix on the keystore file).
# ─────────────────────────────────────────────────────────────
PROPS="$ANDROID_DIR/gradle.properties"
if ! grep -q "SYNCEDIN_RELEASE_STORE_FILE" "$PROPS" 2>/dev/null; then
  echo "→ Writing signing credentials to gradle.properties"
  cat >> "$PROPS" <<EOF

# SyncedIn release signing — generated by scripts/android-release-setup.sh
SYNCEDIN_RELEASE_STORE_FILE=syncedin-upload.jks
SYNCEDIN_RELEASE_KEY_ALIAS=$ALIAS
SYNCEDIN_RELEASE_STORE_PASSWORD=$PASSWORD
SYNCEDIN_RELEASE_KEY_PASSWORD=$PASSWORD
EOF
  echo "✓ gradle.properties updated"
else
  echo "✓ gradle.properties already has signing config — skipping"
fi

# ─────────────────────────────────────────────────────────────
# 3. Patch android/app/build.gradle to add a release signingConfig
#    and apply it to the release buildType. Idempotent — only
#    inserts the block if not already present.
# ─────────────────────────────────────────────────────────────
BUILD_GRADLE="$ANDROID_DIR/app/build.gradle"
if ! grep -q "signingConfigs {" "$BUILD_GRADLE"; then
  echo "→ Patching app/build.gradle with signing config"
  # Insert signingConfigs block right after the `android {` opener.
  python3 - <<PYEOF
import re
from pathlib import Path
p = Path("$BUILD_GRADLE")
s = p.read_text()
block = """    signingConfigs {
        release {
            if (project.hasProperty('SYNCEDIN_RELEASE_STORE_FILE')) {
                storeFile file(SYNCEDIN_RELEASE_STORE_FILE)
                storePassword SYNCEDIN_RELEASE_STORE_PASSWORD
                keyAlias SYNCEDIN_RELEASE_KEY_ALIAS
                keyPassword SYNCEDIN_RELEASE_KEY_PASSWORD
            }
        }
    }
"""
s = re.sub(r"(android\s*\{\s*\n)", r"\\1" + block, s, count=1)
# Apply release signingConfig to the release buildType.
if "signingConfig signingConfigs.release" not in s:
    s = re.sub(
        r"(release\s*\{[^}]*?)(\n\s*\})",
        r"\\1\n            signingConfig signingConfigs.release\\2",
        s,
        count=1,
        flags=re.DOTALL,
    )
p.write_text(s)
print("  ✓ build.gradle patched")
PYEOF
else
  echo "✓ build.gradle already has signingConfigs — skipping"
fi

# ─────────────────────────────────────────────────────────────
# 4. Build the release App Bundle.
# ─────────────────────────────────────────────────────────────
echo ""
echo "→ Building release App Bundle (this takes 2-5 min on first run)"
./gradlew bundleRelease

AAB="$ANDROID_DIR/app/build/outputs/bundle/release/app-release.aab"
if [[ -f "$AAB" ]]; then
  echo ""
  echo "🎉 DONE."
  echo "   Signed bundle: $AAB"
  echo "   Upload this to Play Console → Internal Testing → Create new release."
  echo ""
  echo "   Also save these somewhere safe:"
  echo "   • Keystore file: $KEYSTORE"
  echo "   • Password: $PASSWORD"
else
  echo "✗ Build finished but AAB not found at $AAB — check Gradle output above"
  exit 1
fi
